name: Deploy to AWS Lambda

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    
    - name: Install Templ
      run: go install github.com/a-h/templ/cmd/templ@latest
    
    - name: Install Tailwind CSS
      run: npm install -g tailwindcss
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    
    - name: Generate Templ files
      run: go tool templ generate
    
    - name: Build CSS
      run: tailwindcss -i ./static/assets/css/input.css -o ./static/assets/css/output.css
    
    - name: Build for Lambda ARM64
      run: GOOS=linux GOARCH=arm64 go build -tags lambda,lambda.norpc -o bootstrap .
    
    - name: Create deployment package
      run: |
        zip -r function.zip bootstrap
        zip -r function.zip static/ assets/ content/
    
    - name: Deploy to Lambda
      run: |
        aws lambda update-function-code \
          --function-name function \
          --zip-file fileb://function.zip \
          --region us-east-1
    
    - name: Clean up
      run: rm -f bootstrap function.zip 